export const ROUTES = {
  AUTH: {
    LOGIN:           '/auth/login',
    SET_PASSWORD:    '/auth/set-password',
    SET_PASSWORD_TOKEN: (token = ':token') => `/auth/set-password/${token}`,
    INVITE:          '/auth/invite',
    INVITE_TOKEN:    (token = ':token') => `/auth/invite/${token}`,
    EMPLOYEE_INVITE_SET_PASSWORD: (token = ':token') =>
      `/v1/employee/auth/invitations/${token}/set-password`,
    FORGOT_PASSWORD:        '/auth/forgot-password',
    FORGOT_PASSWORD_VERIFY: '/auth/forgot-password/verify',
    RESET_PASSWORD:         '/auth/reset-password',
    RESET_PASSWORD_TOKEN: (token = ':token') => `/auth/reset-password/${token}`,
    ADMIN_CALLBACK: '/admin/auth/callback',
    ADMIN_OTP:      '/admin/auth/otp',
  },
  DASHBOARD: '/dashboard',
  ADMIN: {
    DASHBOARD:       '/admin-dashboard',
    EMPLOYEES:       '/admin-employees',
    EMPLOYEE_DETAIL: (id = ':id') => `/admin-employees/${id}`,
    DEPARTMENTS:     '/admin-departments',
    JOB_TITLES:      '/admin-job-titles',
    ROLES:           '/admin-roles',
    ROLES_EDIT:      (id = ':id') => `/admin-roles/${id}/edit`,
    EMPLOYEE_ROLES:      '/admin-employee-roles',
    EMPLOYEE_ROLES_EDIT: (id = ':id') => `/admin-employee-roles/${id}/edit`,
    MANAGERS:        '/admin-managers',
    MANAGER_DETAIL:  (id = ':id') => `/admin-managers/${id}`,
    MANAGER_EDIT:    (id = ':id') => `/admin-managers/${id}/edit`,
    PERMISSIONS:     '/admin-permissions',
    SEO_TASK_STATUSES:    '/admin-seo-task-statuses',
    PM_TASK_STATUSES:     '/admin-pm-task-statuses',
    SEO_PROJECT_STATUSES: '/admin-seo-project-statuses',
    PM_PROJECT_STATUSES:  '/admin-pm-project-statuses',
    PROJECT_TYPES:   '/admin-project-types',
    PROJECT_TEMPLATES: '/admin-project-templates',
    SEO_PROJECT_TEMPLATES: '/admin-seo-project-templates',
    INSTRUCTIONS:    '/admin-instructions',
    MESSAGES_MONITOR: '/admin-messages-monitor',
    SETTINGS:        '/admin-org-settings',
  },
  EMPLOYEES: {
    LIST:   '/employees',
    NEW:    '/employees/new',
    DETAIL: (id = ':id') => `/employees/${id}`,
    EDIT:   (id = ':id') => `/employees/${id}/edit`,
  },
  ATTENDANCE: {
    DAILY:      '/attendance',
    LOG:        '/attendance/log',
    EXCEPTIONS: '/attendance/exceptions',
  },
  LEAVES: {
    LIST:   '/leaves',
    DETAIL: (id = ':id') => `/leaves/${id}`,
  },
  PAYROLL: {
    SALARY_SHEET:   '/payroll/salary-sheet',
    DEDUCTIONS:     '/payroll/deductions',
    DEDUCTIONS_NEW: '/payroll/deductions/new',
    BONUSES:        '/payroll/bonuses',
    BONUSES_NEW:    '/payroll/bonuses/new',
    TYPES:          '/payroll/types',
  },
  PROFILE:  '/profile',
  PROFILE_PERMISSIONS: '/profile/permissions',
  UNAUTHORIZED: '/unauthorized',
  MESSAGES: '/messages',
  SETTINGS: '/settings',
  PROJECT_MANAGER: {
    DASHBOARD:    '/project-manager',
    MY_PROJECTS:  '/project-manager/projects',
    TASKS:        '/project-manager/tasks',
    NEW:          '/project-manager/new',
    DETAILS:   (id = ':id') => `/project-manager/project/${id}`,
    INFO:      (id = ':id') => `/project-manager/project/${id}/info`,
    ADD_TASK:  (id = ':id') => `/project-manager/project/${id}/tasks/new`,
    TEAM:      '/project-manager/team',
    TEAM_MEMBER: (id = ':id') => `/project-manager/team/${id}`,
    REPORTS:   '/project-manager/reports',
    WORK_OVERVIEW: '/project-manager/work-overview',
    ATTENDANCE:    '/project-manager/attendance',
    ATTENDANCE_EXCEPTIONS: '/project-manager/attendance-exceptions',
    DEDUCTIONS:    '/project-manager/deductions',
    DEDUCTION_DETAIL: (id = ':id') => `/project-manager/deductions/${id}`,
    BONUSES:       '/project-manager/bonuses',
    BONUS_DETAIL:  (id = ':id') => `/project-manager/bonuses/${id}`,
    TEMPLATES: '/project-manager/templates',
    TASK_STATUSES:    '/project-manager/task-statuses',
    PROJECT_STATUSES: '/project-manager/project-statuses',
    MESSAGES:  '/project-manager/messages',
    PROFILE:   '/project-manager/profile',
  },
  SEO_LEADER: {
    DASHBOARD:    '/seo-leader',
    MY_PROJECTS:  '/seo-leader/projects',
    TASKS:        '/seo-leader/tasks',
    NEW:          '/seo-leader/new',
    DETAILS:   (id = ':id') => `/seo-leader/campaign/${id}`,
    ADD_TASK:  (id = ':id') => `/seo-leader/campaign/${id}/tasks/new`,
    TEAM:      '/seo-leader/team',
    REPORTS:   '/seo-leader/reports',
    WORK_OVERVIEW: '/seo-leader/work-overview',
    ATTENDANCE:    '/seo-leader/attendance',
    ATTENDANCE_EXCEPTIONS: '/seo-leader/attendance-exceptions',
    DEDUCTIONS:    '/seo-leader/deductions',
    DEDUCTION_DETAIL: (id = ':id') => `/seo-leader/deductions/${id}`,
    BONUSES:       '/seo-leader/bonuses',
    BONUS_DETAIL:  (id = ':id') => `/seo-leader/bonuses/${id}`,
    MESSAGES:  '/seo-leader/messages',
    PROFILE:   '/seo-leader/profile',
    TEMPLATES: '/seo-leader/templates',
    TASK_STATUSES:    '/seo-leader/task-statuses',
    PROJECT_STATUSES: '/seo-leader/project-statuses',
  },
  EMPLOYEE: {
    DASHBOARD:     '/employee',
    MY_PROJECTS:   '/employee/projects',
    /** Company messenger (DMs + groups) — /api/v1/employee/messenger */
    MESSAGES:      '/employee/messenger',
    /** HR support tickets — /api/v1/employee/messages (not company messenger) */
    HR_MESSAGES:   '/employee/messages',
    REQUESTS:      '/employee/requests',
    /** Formal HR leave (balance-tracked) */
    LEAVE:         '/employee/leave',
    /** Admin requests to PM manager — /v1/pm/requests */
    ADMIN_REQUESTS:'/employee/admin-requests',
    REPORTS:       '/employee/reports',
    WORK_OVERVIEW:        '/employee/work-overview',
    ATTENDANCE:           '/employee/attendance',
    ATTENDANCE_EXCEPTIONS:'/employee/attendance-exceptions',
    DEDUCTIONS:           '/employee/deductions',
    DEDUCTION_DETAIL:     (id = ':id') => `/employee/deductions/${id}`,
    BONUSES:              '/employee/bonuses',
    BONUS_DETAIL:         (id = ':id') => `/employee/bonuses/${id}`,
    TASKS:         '/pm/tasks',
    PROJECT_TASKS: (projectId: string | number = ':projectId') => `/pm/projects/${projectId}/tasks`,
    TASK_DETAIL:   (projectId: string | number = ':projectId', taskId: string | number = ':taskId') =>
      `/pm/projects/${projectId}/tasks/${taskId}`,
    DAILY_REPORTS: '/employee/daily-reports',
    PROFILE:       '/employee/profile',
    PROJECT_MESSAGES: (projectId: string | number = ':projectId') => `/employee/projects/${projectId}/messages`,
    ALERTS:        '/employee/alerts',
    ALERT_DETAIL:  (id: string | number = ':id') => `/employee/alerts/${id}`,
  },
  SEO_MEMBER: {
    DASHBOARD:     '/seo-member',
    MY_PROJECTS:   '/seo-member/projects',
    NEW:           '/seo-member/projects/new',
    DETAILS:       (id: string | number = ':id') => `/seo-member/projects/${id}`,
    ADD_TASK:      (id: string | number = ':id') => `/seo-member/projects/${id}/tasks/new`,
    TASKS:         '/seo/tasks',
    PROJECT_TASKS: (projectId: string | number = ':projectId') => `/seo/projects/${projectId}/tasks`,
    TASK_DETAIL:   (projectId: string | number = ':projectId', taskId: string | number = ':taskId') =>
      `/seo/projects/${projectId}/tasks/${taskId}`,
    MESSAGES:      '/seo-member/messages',
    REQUESTS:      '/seo-member/requests',
    /** Formal leave (balance-tracked) */
    LEAVE:         '/seo-member/leave',
    /** Admin requests to SEO manager — /v1/seo/requests */
    ADMIN_REQUESTS:'/seo-member/admin-requests',
    REPORTS:       '/seo-member/reports',
    WORK_OVERVIEW: '/seo-member/work-overview',
    ATTENDANCE:    '/seo-member/attendance',
    ATTENDANCE_EXCEPTIONS: '/seo-member/attendance-exceptions',
    DEDUCTIONS:    '/seo-member/deductions',
    DEDUCTION_DETAIL: (id = ':id') => `/seo-member/deductions/${id}`,
    BONUSES:       '/seo-member/bonuses',
    BONUS_DETAIL:  (id = ':id') => `/seo-member/bonuses/${id}`,
    DAILY_REPORTS: '/seo-member/daily-reports',
    PROFILE:       '/seo-member/profile',
  },
} as const;
