export const ROUTES = {
  AUTH: {
    LOGIN:           '/auth/login',
    SET_PASSWORD:    '/auth/set-password',
    SET_PASSWORD_TOKEN: (token = ':token') => `/auth/set-password/${token}`,
    INVITE:          '/auth/invite',
    INVITE_TOKEN:    (token = ':token') => `/auth/invite/${token}`,
    EMPLOYEE_INVITE_SET_PASSWORD: (token = ':token') =>
      `/v1/employee/auth/invitations/${token}/set-password`,
    FORGOT_PASSWORD: '/auth/forgot-password',
    ADMIN_CALLBACK: '/admin/auth/callback',
    ADMIN_OTP:      '/admin/auth/otp',
  },
  DASHBOARD: '/dashboard',
  ADMIN: {
    DASHBOARD:       '/admin-dashboard',
    EMPLOYEES:       '/admin-employees',
    EMPLOYEE_DETAIL: (id = ':id') => `/admin-employees/${id}`,
    DEPARTMENTS:     '/admin-departments',
    JOB_TITLES:      '/admin-job-titles',
    ROLES:           '/admin-roles',
    ROLES_EDIT:      (id = ':id') => `/admin-roles/${id}/edit`,
    MANAGERS:        '/admin-managers',
    PERMISSIONS:     '/admin-permissions',
    SEO_TASK_STATUSES: '/admin-seo-task-statuses',
    SETTINGS:        '/admin-org-settings',
  },
  EMPLOYEES: {
    LIST:   '/employees',
    NEW:    '/employees/new',
    DETAIL: (id = ':id') => `/employees/${id}`,
    EDIT:   (id = ':id') => `/employees/${id}/edit`,
  },
  ATTENDANCE: {
    DAILY: '/attendance',
    LOG:   '/attendance/log',
  },
  LEAVES: {
    LIST:   '/leaves',
    DETAIL: (id = ':id') => `/leaves/${id}`,
  },
  PAYROLL: {
    DEDUCTIONS:     '/payroll/deductions',
    DEDUCTIONS_NEW: '/payroll/deductions/new',
    BONUSES:        '/payroll/bonuses',
    BONUSES_NEW:    '/payroll/bonuses/new',
  },
  PROFILE:  '/profile',
  MESSAGES: '/messages',
  SETTINGS: '/settings',
  PROJECT_MANAGER: {
    DASHBOARD: '/project-manager',
    NEW:       '/project-manager/new',
    DETAILS:   (id = ':id') => `/project-manager/project/${id}`,
    TEAM:      '/project-manager/team',
    REPORTS:   '/project-manager/reports',
    PROFILE:   '/project-manager/profile',
  },
  SEO_LEADER: {
    DASHBOARD: '/seo-leader',
    NEW:       '/seo-leader/new',
    DETAILS:   (id = ':id') => `/seo-leader/campaign/${id}`,
    ADD_TASK:  (id = ':id') => `/seo-leader/campaign/${id}/tasks/new`,
    TEAM:      '/seo-leader/team',
    REPORTS:   '/seo-leader/reports',
    PROFILE:   '/seo-leader/profile',
  },
  EMPLOYEE: {
    DASHBOARD:     '/employee',
    MESSAGES:      '/employee/messages',
    REQUESTS:      '/employee/requests',
    REPORTS:       '/employee/reports',
    TASKS:         '/employee/tasks',
    TASK_DETAIL:   (projectId: string | number = ':projectId', taskId: string | number = ':taskId') =>
      `/employee/tasks/${projectId}/${taskId}`,
    DAILY_REPORTS: '/employee/daily-reports',
    PROFILE:       '/employee/profile',
    PROJECT_MESSAGES: (projectId: string | number = ':projectId') => `/employee/projects/${projectId}/messages`,
  },
  SEO_MEMBER: {
    DASHBOARD:     '/seo-member',
    TASKS:         '/seo-member/tasks',
    TASK_DETAIL:   (projectId: string | number = ':projectId', taskId: string | number = ':taskId') =>
      `/seo-member/tasks/${projectId}/${taskId}`,
    MESSAGES:      '/seo-member/messages',
    REQUESTS:      '/seo-member/requests',
    REPORTS:       '/seo-member/reports',
    DAILY_REPORTS: '/seo-member/daily-reports',
    PROFILE:       '/seo-member/profile',
  },
} as const;
