export const ROUTES = {
  AUTH: {
    LOGIN:           '/auth/login',
    SET_PASSWORD:    '/auth/set-password',
    SET_PASSWORD_TOKEN: (token = ':token') => `/auth/set-password/${token}`,
    INVITE:          '/auth/invite',
    INVITE_TOKEN:    (token = ':token') => `/auth/invite/${token}`,
    EMPLOYEE_INVITE_SET_PASSWORD: (token = ':token') =>
      `/v1/employee/auth/invitations/${token}/set-password`,
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD:  '/auth/reset-password',
    RESET_PASSWORD_TOKEN: (token = ':token') => `/auth/reset-password/${token}`,
    ADMIN_CALLBACK: '/admin/auth/callback',
    ADMIN_OTP:      '/admin/auth/otp',
  },
  DASHBOARD: '/dashboard',
  ADMIN: {
    DASHBOARD:       '/admin-dashboard',
    EMPLOYEES:       '/admin-employees',
    EMPLOYEE_DETAIL: (id = ':id') => `/admin-employees/${id}`,
    DEPARTMENTS:     '/admin-departments',
    JOB_TITLES:      '/admin-job-titles',
    ROLES:           '/admin-roles',
    ROLES_EDIT:      (id = ':id') => `/admin-roles/${id}/edit`,
    MANAGERS:        '/admin-managers',
    MANAGER_DETAIL:  (id = ':id') => `/admin-managers/${id}`,
    PERMISSIONS:     '/admin-permissions',
    SEO_TASK_STATUSES: '/admin-seo-task-statuses',
    PROJECT_TYPES:   '/admin-project-types',
    INSTRUCTIONS:    '/admin-instructions',
    MESSAGES_MONITOR: '/admin-messages-monitor',
    SETTINGS:        '/admin-org-settings',
  },
  EMPLOYEES: {
    LIST:   '/employees',
    NEW:    '/employees/new',
    DETAIL: (id = ':id') => `/employees/${id}`,
    EDIT:   (id = ':id') => `/employees/${id}/edit`,
  },
  ATTENDANCE: {
    DAILY: '/attendance',
    LOG:   '/attendance/log',
  },
  LEAVES: {
    LIST:   '/leaves',
    DETAIL: (id = ':id') => `/leaves/${id}`,
  },
  PAYROLL: {
    DEDUCTIONS:     '/payroll/deductions',
    DEDUCTIONS_NEW: '/payroll/deductions/new',
    BONUSES:        '/payroll/bonuses',
    BONUSES_NEW:    '/payroll/bonuses/new',
  },
  PROFILE:  '/profile',
  PROFILE_PERMISSIONS: '/profile/permissions',
  UNAUTHORIZED: '/unauthorized',
  MESSAGES: '/messages',
  SETTINGS: '/settings',
  PROJECT_MANAGER: {
    DASHBOARD:    '/project-manager',
    MY_PROJECTS:  '/project-manager/projects',
    TASKS:        '/project-manager/tasks',
    NEW:          '/project-manager/new',
    DETAILS:   (id = ':id') => `/project-manager/project/${id}`,
    INFO:      (id = ':id') => `/project-manager/project/${id}/info`,
    ADD_TASK:  (id = ':id') => `/project-manager/project/${id}/tasks/new`,
    TEAM:      '/project-manager/team',
    TEAM_MEMBER: (id = ':id') => `/project-manager/team/${id}`,
    REPORTS:   '/project-manager/reports',
    TEMPLATES: '/project-manager/templates',
    PROFILE:   '/project-manager/profile',
  },
  SEO_LEADER: {
    DASHBOARD:    '/seo-leader',
    MY_PROJECTS:  '/seo-leader/projects',
    TASKS:        '/seo-leader/tasks',
    NEW:          '/seo-leader/new',
    DETAILS:   (id = ':id') => `/seo-leader/campaign/${id}`,
    ADD_TASK:  (id = ':id') => `/seo-leader/campaign/${id}/tasks/new`,
    TEAM:      '/seo-leader/team',
    REPORTS:   '/seo-leader/reports',
    PROFILE:   '/seo-leader/profile',
  },
  EMPLOYEE: {
    DASHBOARD:     '/employee',
    MY_PROJECTS:   '/employee/projects',
    MESSAGES:      '/employee/messages',
    REQUESTS:      '/employee/requests',
    REPORTS:       '/employee/reports',
    TASKS:         '/pm/tasks',
    PROJECT_TASKS: (projectId: string | number = ':projectId') => `/pm/projects/${projectId}/tasks`,
    TASK_DETAIL:   (projectId: string | number = ':projectId', taskId: string | number = ':taskId') =>
      `/pm/projects/${projectId}/tasks/${taskId}`,
    DAILY_REPORTS: '/employee/daily-reports',
    PROFILE:       '/employee/profile',
    PROJECT_MESSAGES: (projectId: string | number = ':projectId') => `/employee/projects/${projectId}/messages`,
    ALERTS:        '/employee/alerts',
    ALERT_DETAIL:  (id: string | number = ':id') => `/employee/alerts/${id}`,
  },
  SEO_MEMBER: {
    DASHBOARD:     '/seo-member',
    MY_PROJECTS:   '/seo-member/projects',
    TASKS:         '/seo/tasks',
    PROJECT_TASKS: (projectId: string | number = ':projectId') => `/seo/projects/${projectId}/tasks`,
    TASK_DETAIL:   (projectId: string | number = ':projectId', taskId: string | number = ':taskId') =>
      `/seo/projects/${projectId}/tasks/${taskId}`,
    MESSAGES:      '/seo-member/messages',
    REQUESTS:      '/seo-member/requests',
    REPORTS:       '/seo-member/reports',
    DAILY_REPORTS: '/seo-member/daily-reports',
    PROFILE:       '/seo-member/profile',
  },
} as const;
